# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests


!pip install gmaps
import gmaps

# Import Google API key
# from config import g_key
g_key = "AIzaSyDRdGdu3o07UxJHAE8cQsFryBb8E_Vz-qA"
# Configure gmaps
#import googlemaps
gmaps.configure(api_key=g_key)

Requirement already satisfied: gmaps in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (0.9.0)
Requirement already satisfied: geojson>=2.0.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.6.5)
Requirement already satisfied: ipython>=5.3.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.31.1)
Requirement already satisfied: six in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (1.12.0)
Requirement already satisfied: traitlets>=4.3.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: backcall in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: pygments in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (2.11.2)
Requirement already satisfied: matplotlib-inline in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: pickleshare in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: jedi>=0.16 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.18.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (61.2.0)
Requirement already satisfied: decorator in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (5.1.1)
Requirement already satisfied: colorama in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.4.4)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.2)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (6.9.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.12)
Requirement already satisfied: nest-asyncio in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.5)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (4.9.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.2)
Requirement already satisfied: pyzmq>=13 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (22.3.0)
Requirement already satisfied: pywin32>=1.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (302)
Requirement already satisfied: jsonschema>=2.6 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.4.0)
Requirement already satisfied: fastjsonschema in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (2.15.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.4.0)
Requirement already satisfied: typing-extensions in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.1.1)
Requirement already satisfied: importlib-metadata in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.11.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: importlib-resources>=1.4.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (5.2.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from importlib-resources>=1.4.0->jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.7.0)
Requirement already satisfied: wcwidth in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.8)
Requirement already satisfied: jinja2 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: nbconvert in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.4)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: prometheus-client in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: argon2-cffi in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.15.0)
Requirement already satisfied: pycparser in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.21)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: bleach in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.1.0)
Requirement already satisfied: testpath in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.13)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4)
Requirement already satisfied: defusedxml in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: beautifulsoup4 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from beautifulsoup4->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.3.1)
Requirement already satisfied: webencodings in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: packaging in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\14064\anaconda3\envs\pythondata\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.0.4)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Paramonga,PE,-10.6667,-77.8333,68.11,78,97,4.79,overcast clouds
1,1,Rikitea,PF,-23.1203,-134.9692,73.69,76,74,13.18,broken clouds
2,2,Faya,SA,18.3851,42.4509,53.98,57,0,2.59,clear sky
3,3,Dikson,RU,73.5069,80.5464,-2.79,100,72,3.69,broken clouds
4,4,Punta Arenas,CL,-53.1500,-70.9167,42.12,75,59,19.64,broken clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would perfer on your vacation? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would perfer on your vacation? "))

What is the minimum temperature you would perfer on your vacation? 65
What is the maximum temperature you would perfer on your vacation? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [4]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                    
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Paramonga,PE,-10.6667,-77.8333,68.11,78,97,4.79,overcast clouds
1,1,Rikitea,PF,-23.1203,-134.9692,73.69,76,74,13.18,broken clouds
6,6,Sao Miguel Do Araguaia,BR,-13.2750,-50.1628,72.34,90,99,4.27,overcast clouds
7,7,Manavalakurichi,IN,8.1333,77.3000,80.40,75,97,4.79,overcast clouds
12,12,Caravelas,BR,-17.7125,-39.2481,73.54,95,100,9.19,light rain
13,13,Trairi,BR,-3.2778,-39.2689,77.25,78,100,4.21,overcast clouds
15,15,Hirara,JP,24.8000,125.2833,78.73,80,0,12.62,clear sky
18,18,Kieta,PG,-6.2167,155.6333,81.59,81,100,3.20,light rain
19,19,Kapaa,US,22.0752,-159.3190,73.47,96,95,3.00,moderate rain
20,20,Esperance,AU,-33.8667,121.9000,71.06,47,0,7.94,clear sky

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [5]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities_df = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Paramonga,PE,-10.6667,-77.8333,68.11,78,97,4.79,overcast clouds
1,1,Rikitea,PF,-23.1203,-134.9692,73.69,76,74,13.18,broken clouds
6,6,Sao Miguel Do Araguaia,BR,-13.2750,-50.1628,72.34,90,99,4.27,overcast clouds
7,7,Manavalakurichi,IN,8.1333,77.3000,80.40,75,97,4.79,overcast clouds
12,12,Caravelas,BR,-17.7125,-39.2481,73.54,95,100,9.19,light rain
...,...,...,...,...,...,...,...,...,...,...
695,695,Kindu,CD,-2.9500,25.9500,65.59,99,100,0.87,overcast clouds
696,696,Kupang,ID,-10.1667,123.5833,84.78,84,75,5.75,broken clouds
697,697,San Vicente De Canete,PE,-13.0751,-76.3835,67.33,87,86,2.80,overcast clouds
698,698,Dingle,PH,10.9995,122.6711,85.41,70,52,13.24,broken clouds
704,704,Maragogi,BR,-9.0122,-35.2225,76.75,81,86,9.73,light rain

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [6]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng", "Weather Description"]].copy()

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Weather Description
0,Paramonga,PE,68.11,-10.6667,-77.8333,overcast clouds
1,Rikitea,PF,73.69,-23.1203,-134.9692,broken clouds
6,Sao Miguel Do Araguaia,BR,72.34,-13.2750,-50.1628,overcast clouds
7,Manavalakurichi,IN,80.40,8.1333,77.3000,overcast clouds
12,Caravelas,BR,73.54,-17.7125,-39.2481,light rain
13,Trairi,BR,77.25,-3.2778,-39.2689,overcast clouds
15,Hirara,JP,78.73,24.8000,125.2833,clear sky
18,Kieta,PG,81.59,-6.2167,155.6333,light rain
19,Kapaa,US,73.47,22.0752,-159.3190,moderate rain
20,Esperance,AU,71.06,-33.8667,121.9000,clear sky

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [7]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Weather Description,Hotel Name
0,Paramonga,PE,68.11,-10.6667,-77.8333,overcast clouds,
1,Rikitea,PF,73.69,-23.1203,-134.9692,broken clouds,
6,Sao Miguel Do Araguaia,BR,72.34,-13.2750,-50.1628,overcast clouds,
7,Manavalakurichi,IN,80.40,8.1333,77.3000,overcast clouds,
12,Caravelas,BR,73.54,-17.7125,-39.2481,light rain,
13,Trairi,BR,77.25,-3.2778,-39.2689,overcast clouds,
15,Hirara,JP,78.73,24.8000,125.2833,clear sky,
18,Kieta,PG,81.59,-6.2167,155.6333,light rain,
19,Kapaa,US,73.47,22.0752,-159.3190,moderate rain,
20,Esperance,AU,71.06,-33.8667,121.9000,clear sky,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [8]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [9]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# Display sample data
hotel_df.head()

,City,Country,Max Temp,Lat,Lng,Weather Description,Hotel Name
0,Paramonga,PE,68.11,-10.6667,-77.8333,overcast clouds,"Av Douglas Stephen, Los Chalets Paramonga, Lim..."
1,Rikitea,PF,73.69,-23.1203,-134.9692,broken clouds,People ThankYou
6,Sao Miguel Do Araguaia,BR,72.34,-13.2750,-50.1628,overcast clouds,Hotel Executivo Palace
7,Manavalakurichi,IN,80.40,8.1333,77.3000,overcast clouds,Jebinrio home
12,Caravelas,BR,73.54,-17.7125,-39.2481,light rain,Pousada dos Navegantes

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [11]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = clean_hotel_df = hotel_df.dropna(axis="index", how="any")

# Display sample data
clean_hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Weather Description,Hotel Name
0,Paramonga,PE,68.11,-10.6667,-77.8333,overcast clouds,"Av Douglas Stephen, Los Chalets Paramonga, Lim..."
1,Rikitea,PF,73.69,-23.1203,-134.9692,broken clouds,People ThankYou
6,Sao Miguel Do Araguaia,BR,72.34,-13.2750,-50.1628,overcast clouds,Hotel Executivo Palace
7,Manavalakurichi,IN,80.40,8.1333,77.3000,overcast clouds,Jebinrio home
12,Caravelas,BR,73.54,-17.7125,-39.2481,light rain,Pousada dos Navegantes
13,Trairi,BR,77.25,-3.2778,-39.2689,overcast clouds,janelas do mar
15,Hirara,JP,78.73,24.8000,125.2833,clear sky,Hotel Atoll Emerald Miyakojima
18,Kieta,PG,81.59,-6.2167,155.6333,light rain,Uruna Bay Retreat
19,Kapaa,US,73.47,22.0752,-159.3190,moderate rain,Sheraton Kauai Coconut Beach Resort
20,Esperance,AU,71.06,-33.8667,121.9000,clear sky,Hospitality Esperance

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [12]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [13]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label='City_ID')

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [14]:
# Review the formatting template provided
info_box_template = """

Hotel Name
{Hotel Name}

City
{City}
Country
{Country}
 Weather
{Weather Description} and {Max Temp} °F


"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [15]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n\nHotel Name\nAv Douglas Stephen, Los Chalets Paramonga, Lima, Perú\n\nCity\nParamonga\nCountry\nPE\n Weather\novercast clouds and 68.11 °F\n\n\n',
 '\n\nHotel Name\nPeople ThankYou\n\nCity\nRikitea\nCountry\nPF\n Weather\nbroken clouds and 73.69 °F\n\n\n',
 '\n\nHotel Name\nHotel Executivo Palace\n\nCity\nSao Miguel Do Araguaia\nCountry\nBR\n Weather\novercast clouds and 72.34 °F\n\n\n',
 '\n\nHotel Name\nJebinrio home\n\nCity\nManavalakurichi\nCountry\nIN\n Weather\novercast clouds and 80.4 °F\n\n\n',
 '\n\nHotel Name\nPousada dos Navegantes\n\nCity\nCaravelas\nCountry\nBR\n Weather\nlight rain and 73.54 °F\n\n\n',
 '\n\nHotel Name\njanelas do mar\n\nCity\nTrairi\nCountry\nBR\n Weather\novercast clouds and 77.25 °F\n\n\n',
 '\n\nHotel Name\nHotel Atoll Emerald Miyakojima\n\nCity\nHirara\nCountry\nJP\n Weather\nclear sky and 78.73 °F\n\n\n',
 '\n\nHotel Name\nUruna Bay Retreat\n\nCity\nKieta\nCountry\nPG\n Weather\nlight rain and 81.59 °F\n\n\n',
 '\n\nHotel Name\nSheraton Kauai Coconut Beach Resort\n\nCity\nKapaa\nCountry\nUS\n Weather\nmoderate rain and 73.47 °F\n\n\n',
 '\n\nHotel Name\nHospitality Esperance\n\nCity\nEsperance\nCountry\nAU\n Weather\nclear sky and 71.06 °F\n\n\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [16]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
0  -10.6667  -77.8333
1  -23.1203 -134.9692
6  -13.2750  -50.1628
7    8.1333   77.3000
12 -17.7125  -39.2481
13  -3.2778  -39.2689
15  24.8000  125.2833
18  -6.2167  155.6333
19  22.0752 -159.3190
20 -33.8667  121.9000

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [18]:
# Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Create a figure to add the Google map as a layer
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))